Add tutorial how to program android apps
bmwcarit/ramses-composer-docs pull request #33
Opened 2022-07-03 20:30 UTC by violinyanev

Includes:

* Detailed step-by-step guide how to write a ramses app
* Formatted code snippets with explanations
* The source code of the "final" app

2022-07-04 06:06 UTC, bojackHaasman requested changes
In general very cool tutorial.
one remark: maybe state in which file you are operating everytime before you explain code

2022-07-04 06:06 UTC, bojackHaasman commented on basics/android_app/app_src/app/src/main/java/com/example/myapplication/MonkeyThread.kt
> +        lightId?.set((frame / 60) % 3)
this will overflow at some point right?

2022-07-04 10:50 UTC, bojackHaasman requested changes

2022-07-04 10:50 UTC, bojackHaasman commented on basics/android_app/app_src/app/build.gradle
> +    implementation "io.github.bmwcarit:ramses-aar:1.0.3"
go over dependencies again and verify which ones you really need

2022-07-04 10:50 UTC, bojackHaasman commented on basics/android_app/app_src/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        val surfaceView = findViewById<SurfaceView>(R.id.surfaceView)
pls add comment that ramses renders to the surface of the surfaceview

2022-07-04 10:50 UTC, bojackHaasman commented on basics/android_app/app_src/build.gradle
> +    id 'com.android.library' version '7.2.0' apply false
do you need this? we don't have a library module in the ramses-composer repo, right?

2022-07-04 10:50 UTC, bojackHaasman commented on basics/android_app/app_src/settings.gradle
> +}
do you know how this works, I have never seen this part

2022-07-05 14:57 UTC, ParadoxDaKo approved these changes
Seems OK (from Ramses Composer side)

2022-07-05 15:49 UTC, merged