Added links to the example projects to the top of each tutorial chapter
bmwcarit/ramses-composer-docs pull request #46
Opened 2022-10-26 14:14 UTC by paradoxSW

2022-10-26 15:48 UTC, violinyanev requested changes
Also, maybe worth adding a link to the trace player data?

2022-10-26 15:48 UTC, violinyanev commented on doc/basics/introduction/README.md
> +*You can find the example project [here](https://github.com/bmwcarit/ramses-composer-docs/tree/master/doc/basics/introduction).*
this is not really an example project, think we should remove the link

2022-10-26 15:48 UTC, violinyanev commented on doc/basics/lua_syntax/README.md
> +*You can find the example project [here](https://github.com/bmwcarit/ramses-composer-docs/tree/master/doc/basics/lua_syntax).*
same, no example project here

2022-10-27 06:36 UTC, paradoxSW commented
Fixed both links.
Not sure about the trace player, there is only the tracefile inside the traces folder, which is already linked at the end of the tutorial

2022-10-27 11:18 UTC, violinyanev approved these changes

2022-10-27 11:19 UTC, merged