Ramses Composer v1.5.0 features documentation
bmwcarit/ramses-composer-docs pull request #59
Opened 2023-02-10 13:37 UTC by vmalkov-pdx

This PR brings Ramses Composer documentation update for features introduced in v1.5

Topics covered:
- Dynamic render order control
- MSAA multisampling
- BlitPass
- Array and Struct uniforms in shaders
- SaveAs with new ID

2023-02-16 13:48 UTC, violinyanev requested changes

2023-02-16 13:48 UTC, violinyanev commented on doc/basics/multisampling/shaders/multisampler.frag
> +}
eol missing, also in other files

2023-02-16 20:05 UTC, vmalkov-pdx commented on doc/advanced/external_references/README.md
> +the street goes straight through the camera. In order to fix this, translate the camera 5 units up on the y-axis and rotate
It felt like a typo, because normally degrees are used for angles. I'll revert this change if degrees are fine.

2023-02-17 09:47 UTC, violinyanev approved these changes

2023-02-17 10:11 UTC, merged