Skinning
bmwcarit/ramses-composer-docs pull request #62
Opened 2023-03-02 11:40 UTC by webermm

Added documentation for skinning feature in v1.6.0.

2023-03-02 12:22 UTC, violinyanev requested changes

2023-03-02 12:22 UTC, violinyanev commented on doc/advanced/skinning/README.md
> +As a starting point for setting up a shader for a skinned mesh a template shader is included in the RamsesComposer distribution in the `resources/shaders/` subfolder. The fragment shader is
```suggestion
As a starting point for setting up a shader for a skinned mesh a template shader is included in the RamsesComposer distribution in the `resources/shaders/` subfolder. The fragment shader can look like this for example:
```

2023-03-02 12:22 UTC, violinyanev commented on doc/advanced/skinning/README.md
> +However the exmple glTF file used already contains an animation which controls the rotation of the `node_2` in the skeleton node hierarchy via a link:
```suggestion
The exmple glTF file used already contains an animation which controls the rotation of the `node_2` in the skeleton node hierarchy via a link:
```

2023-03-09 16:47 UTC, violinyanev submitted a review, later dismissed

2023-03-09 16:48 UTC, violinyanev commented
Can't have links in the PR, they don't work of course. See github actions result

2023-03-21 12:43 UTC, vmalkov-pdx commented on doc/advanced/skinning/skinning-simple.rca
> +                "uri": "../../../../../OneDrive - Paradox Cat GmbH/Documents/RamsesComposer/skinning/scripts/clip-timer.lua"
This script seems to be missing.

2023-03-24 22:54 UTC, closed without merging

2023-03-24 22:54 UTC, vmalkov-pdx commented
PR closed since changes are merged in main Ramses Composer development repo.