Morphing
bmwcarit/ramses-composer-docs pull request #63
Opened 2023-03-02 11:44 UTC by webermm

Added chapter describing morphing introduced in v1.6.0.

2023-03-02 12:17 UTC, violinyanev requested changes

2023-03-02 12:17 UTC, violinyanev commented on doc/advanced/morphing/README.md
> +To make use the additional morph target vertex attributes a specialized shader needs to be supplied. A template shader is included with the RamsesComposer distribution. The vertex shader is reproduce
```suggestion
To make use the additional morph target vertex attributes a specialized shader needs to be supplied. A template shader is included with the RamsesComposer distribution. For example, the vertex shader can look like this:
```

2023-03-07 14:18 UTC, violinyanev approved these changes

2023-03-24 22:55 UTC, vmalkov-pdx commented
PR closed since changes are merged to main Ramses Composer repo.

2023-03-24 22:55 UTC, closed without merging